# Generated by Django 4.1.3 on 2023-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartproduct_orderproduct_userorder_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
